export { default as APP_LOGO_PATH } from '@renderer/assets/logo.svg'
export const APP_NAME = 'MkApi'
export const APP_VERSION = '1.0.0'
export const LOCAL_KEY_PROJECT = 'project:key'
export const API_STATE_SESSION = 'api:state'
